### ISSUE TITLE
foo() should be converted to self.foo instead of foo as needed

### ISSUE THREAD

**Issue by sgrif** [penelopezone/rubyfmt#130]
* Ruby version: 
* Rubyfmt git sha: Asking Penelope if this was handled on Twitter

## Input file

```ruby
foo = foo()
```

## Rubyfmt's output

```
foo = foo
```

## This breaks because

`foo` is not always semantically equivalent to `foo()`. If there is a local with that name, it should be converted to `self.foo`, which is equivalent, instead

**Comment by fables-tales** [comment]
Fixed in #287
