### ISSUE TITLE
Removes space after interpolation in squiggly heredoc

### ISSUE THREAD

**Issue by coreyja** [penelopezone/rubyfmt#138]
* Ruby version: ruby 2.6.2p47
* Rubyfmt git sha: 86329658d8d0f5fc7ec34c513ea344890df5bb08

## Input file

```ruby
p <<~TXT
  #{'foo'} bar
TXT
```

## Rubyfmt's output

```ruby
p(<<~TXT)
#{"foo"}bar
TXT
```

## This breaks because

`rubyfmt` has removed the space after the interpolation.

It appears unique to the squiggly heredoc `<<~`. I can not reproduce this with the 'normal' heredoc `<<-`

**Comment by samphippen** [comment]
confirmed this is a real bug

**Comment by penelopezone** [comment]
this is a ripper bug, it elides two spaces off TStringContents after embed expressions for some reason

**Comment by reese** [comment]
This is fixed by #343 (see 34644f938710b3aa7bebeaa2e75bf85fefc6f056 specifically)
