### ISSUE TITLE
Work incorrect with hash argument inside block

### ISSUE THREAD

**Issue by cuongn265** [penelopezone/rubyfmt#151]
* Ruby version: 2.6.2
* Rubyfmt git sha: [3f71cc3b302b33265c1532de601a23a73eaa5abd](https://github.com/penelopezone/rubyfmt/commit/3f71cc3b302b33265c1532de601a23a73eaa5abd)

## Input file

```ruby
member.update_attributes(  role: "owner")

[1..2].each do |a|
  member.update_attributes(  role: "owner")
end
```

## Rubyfmt's output

```ruby
member.update_attributes(role: "owner")

[1..2].each do |a|
  member.update_attributes(  role: "owner")
end
```

## This breaks because
I'm not sure

Fill out this section with what Rubyfmt should have done.

**Comment by phoet** [comment]
just gave rubyfmt a try and unfortunately that error occured in the first file i formatted...

**Comment by penelopezone** [comment]
this is fixed in our rust build.
