### ISSUE TITLE
multiple heredocs get squished

### ISSUE THREAD

**Issue by robotdana** [penelopezone/rubyfmt#152]
* Ruby version: 2.6.5
* Rubyfmt git sha: 374e59e955c6b1883af33075eae61c658b017b50

## Input file

```ruby
method_call(
  <<~TEXT,
    a multiline text string
    with another line
  TEXT
  <<~ANOTHER_TEXT,
    with more lines
  ANOTHER_TEXT
)
```

## Rubyfmt's output

```ruby
method_call(<<~TEXT, <<~ANOTHER_TEXT)
with more lines
a multiline text string
with another line
TEXT
ANOTHER_TEXT
```

(same behaviour for `<<-` heredocs

## This breaks because

the contents of the second heredoc is moved to the first heredoc

Fill out this section with what Rubyfmt should have done.

I think it was already correct?

**Comment by robotdana** [comment]
i'm surprised that this also would be a correct program, but maybe this is what it should be doing
```
puts(<<~TEXT, <<~ANOTHER_TEXT)
  with more lines
  a multiline text string
TEXT
  with another line
ANOTHER_TEXT
```

**Comment by penelopezone** [comment]
Yeah, we should produce this last example, it's a bug.

**Comment by fables-tales** [comment]
@robotdana I think this is now fixed on master, could you take a look?

**Comment by fables-tales** [comment]
closing, confirmed this is fixed
