### ISSUE TITLE
Should Rubyfmt map stabby lambdas to method lambda

### ISSUE THREAD

**Issue by penelopezone** [penelopezone/rubyfmt#159]
In Ruby, `lambda` is a method call (yup, it's not a keyword). Lambda takes a block with the normal `do...end` or `{...}` syntax. We also have stabby lambdas, which are of the form `-> (...) { ... }`. They don't take the usual `|` block args, this makes them "different".

I am considering autoformatting stabby lambdas in user inputs to "method" lambdas, so

`-> (x) { x }` becomes: `lambda { |x| x }`.

Is this a good idea?

**Comment by chrisseaton** [comment]
> `-> (x) { x }` becomes: `lambda { |x| x }`

These two things don't have the same semantics, do they? As you already said, one is a method call and the other isn't. Does Rubyfmt change program semantics? I think it'd be best if it didn't. I've had problems with Rubocop rules making my program behave differently.

**Comment by tenderlove** [comment]
`lambda blah` is way too long when you're writing callbacks in Rails

**Comment by noelrappin** [comment]
Ok. FWIW, I personally like stabby lambdas and I would hate to see them get formatted away. That said, they are, of course, weird, so if other people feel like the consistency is more important.

I do wonder, and I'm not 100% sure, what people who come to Ruby from other languages find more readable..

**Comment by penelopezone** [comment]
@chrisseaton I guess the user overrides the lambda method...........

**Comment by penelopezone** [comment]
@chrisseaton points out that if the user overrides the lambda method, these have different semantics, and therefore rubyfmt could break a user's program. I don't *think* this is very common, but we have a "never break the user" attitude, so, this will not happen.

**Comment by tenderlove** [comment]
Just don't `flipflop` on this decision. 😆
