### ISSUE TITLE
Method call chain dropping

### ISSUE THREAD

**Issue by penelopezone** [penelopezone/rubyfmt#187]
Hi Folks,

I recently ran rubyfmt through a large rails app, and one thing that it did that I wasn't happy with was leaving long activerecord scopes all on a single line, regardless of whether the user did line breaking. Consider:

```ruby
def foo
  SomeCollection.a.very.long.dotchain.with.lots.of.different.character.lengths.in.the.disestablishmentarianism.method.call.omg.so.long.justin.why
  SomeCollection.a.very.long(argument1: bees).dotchain.with.lots.of.different.character.lengths.in.the.disestablishmentarianism.method.call.omg.so.long.justin.why
  SomeCollection.a.very.long(argument1: bees,but: what,if: i,have: to,drop: it,oh: my,god: please,stop: me).dotchain.with.lots.of.different.character.lengths.in.the.disestablishmentarianism.method.call.omg.so.long.justin.why
end
```

the first line will be formatted as:

```ruby
SomeCollection
  .a
  .very
  .long
  .dotchain
  .with
  .lots
  .of
  .different
  .character
  .lengths
  .in
  .the
  .disestablishmentarianism
  .method
  .call
  .omg
  .so
  .long
  .justin
  .why
```

The second is ambiguous, but should probably be:

```ruby
SomeCollection
  .a
  .very
  .long(argument1: bees.baz)
  .dotchain
  .with
  .lots
  .of
  .different
  .character
  .lengths
  .in
  .the
  .disestablishmentarianism
  .method
  .call
  .omg
  .so
  .long
  .justin
  .why
```

The third I am very unsure about but like:
```ruby
SomeCollection
  .a
  .very
  .long(
    argument1: bees.baz,
    but: what,
    if: i,
    have: to,
    drop: it,
    oh: my,
    god: please,
    stop: me
  )
  .dotchain
  .with
  .lots
  .of
  .different
  .character
  .lengths
  .in
  .the
  .disestablishmentarianism
  .method
  .call
  .omg
  .so
  .long
  .justin
  .why
```

Please provide feedback!!

/cc @bestie @tenderlove @sgrif

**Comment by tenderlove** [comment]
I'm a fan of the chained newline thing, but only if the line is > 80 width (or whatever width folks on the team prefer).  Same goes for things like:

```ruby
  .long(
    argument1: bees.baz,
    but: what,
    if: i,
    have: to,
    drop: it,
    oh: my,
    god: please,
    stop: me
  )
```

If it fits the width, keep it there, otherwise do this.

**Comment by JonRowe** [comment]
I'm with Aaron here as long as `omg.so.long.justin.why` is always formatted as one line on the end.

**Comment by mcmire** [comment]
I'm also with @tenderlove as well. That's pretty much my exact rule. If it fits on one line, keep it on one line, but a method call doesn't fit, split the call up. So for instance, this would not get reformatted:

``` ruby
SomeModel.active.with_colors('red', 'blue', 'green').summa_cum_laude
```

but as soon as this exceeds 80 characters:

``` ruby
SomeModel.active.with_colors('red', 'blue', 'green').summa_cum_laude.peanut_butter_and_jelly
```

then the chain gets split:

``` ruby
SomeModel
  .active
  .with_colors('red', 'blue', 'green')
  .summa_cum_laude
  .peanut_butter_and_jelly
```

As with a non-method chain, an argument for a single method call doesn't get split until _that_ argument exceeds 80 characters. This goes for keyword arguments too. So this would stay:

``` ruby
SomeModel
  .active
  .with_colors('red', 'green', 'blue', one: 'fish', two: 'fish')
  .summa_cum_laude
  .peanut_butter_and_jelly
```

but this would get broken up

``` ruby
SomeModel
  .active
  .with_colors('red', ['green', 'blue'], one: 'fish', two: 'fish', red: 'fish', blue: 'fish')
  .summa_cum_laude
  .peanut_butter_and_jelly
```

into:

``` ruby
SomeModel
  .active
  .with_colors(
    'red',
    ['green', 'blue'],
    one: 'fish',
    two: 'fish',
    red: 'fish',
    blue: 'fish'
  )
  .summa_cum_laude
  .peanut_butter_and_jelly
```

Again, note how the array isn't broken up until _it_ exceeds 80 characters. So this

``` ruby
SomeModel
  .active
  .with_colors(
    'red',
    ['green', 'blue', 'and', 'a', { partridge: 'in', a: 'pear', tree: 'and', things: 'and', stuff: 'yeah' }],
    one: 'fish',
    two: 'fish',
    red: 'fish',
    blue: 'fish'
  )
  .summa_cum_laude
  .peanut_butter_and_jelly
```

becomes:

``` ruby
SomeModel
  .active
  .with_colors(
    'red',
    [
      'green',
      'blue',
      'and',
      'a',
      { partridge: 'in', a: 'pear', tree: 'and', things: 'and', stuff: 'yeah' }
    ],
    one: 'fish',
    two: 'fish',
    red: 'fish',
    blue: 'fish'
  )
  .summa_cum_laude
  .peanut_butter_and_jelly
```

(It's possible that rubyfmt accounts for some of this already, but that's how it would fit into method call chains.)

**Comment by penelopezone** [comment]
@mcmire  yes you've done exactly what I want to do, just dumping some of this stuff was helpful, thanks!

**Comment by noelrappin** [comment]
Pretty sure what @mcmire suggests is basically what the new version of Prettier does, and I like that. I used to personally put two things on one line on the grounds that it was still easy to read and saved some vertical space, but ultimately I decided that was kind of silly and now I basically do what @mcmire does. Where did you wind up on line width, by the way?

**Comment by bestie** [comment]
What we're calling 'the @mcmire' method is not offensive and I would be totally ok is that behaviour however, I like the simplicity of all chains getting new lines and there being fewer ways of formatting code.

Also I think this declarative / configuration-like code benefits from all the white space it can possibly get.

**Comment by sgrif** [comment]
I would use number of chained calls as a metric here too, not just character count. If something is 4+ chained method calls, I'd want it broken up even if it doesn't total to 80 characters

**Comment by penelopezone** [comment]
@bestie can you show an example of what you mean?

**Comment by penelopezone** [comment]
@sgrif rubyfmt largely only pays attention to what the user has done (if the user broke a construct, we break that construct).

I am experimenting with 120 characters as a limit, but I haven't made my mind up yet.
