### ISSUE TITLE
Deletes comments within arrays

### ISSUE THREAD

**Issue by robotdana** [penelopezone/rubyfmt#188]
* Ruby version: 2.7
* Rubyfmt git sha: acade99e80a18b0dcbec1ba908bb37c9301857bb

## Input file

```ruby
[
  "item1", # comment relevant to item 1
  "item2", # comment relevant to item 2
  "item3", "item4" # comment relevant to item 3 and 4
]
```

## Rubyfmt's output

```ruby
[
  "item1",
  "item2",
  "item3",
  "item4"
]
```

## This breaks because

The comments are dropped on the floor, never to be seen again. I'm not sure if you consider removing comments to be technically breaking the code at all because they don't affect passing specs/tests, but to me comments are an essential part of the code and rubyfmt shouldn't lose them even if it maybe moves them around a bit

## in order of what i'd ideally like to happen:
1. keep them inline (currently when rubyfmt'd, this also drops comments)
```ruby
[
  "item1", # comment relevant to item 1
  "item2", # comment relevant to item 2
  "item3", 
  "item4" # comment relevant to item 3 and 4
]
```
or (I have no preference here, deciding where the comment goes seems like it would require sentience)
```ruby
[
  "item1", # comment relevant to item 1
  "item2", # comment relevant to item 2
  "item3",  # comment relevant to item 3 and 4
  "item4"
]
```
2. or if comments should be on their own lines i'd like the comments moved above the line they were on, as that to me still connects the comment with the commented code.
(when rubyfmt'd this currently moves comments to the lines above the array open, (looks like the subsequent option but keeps the indentation))
```ruby
[
  # comment relevant to item 1
  "item1", 
  # comment relevant to item 2
  "item2", 
  # comment relevant to item 3 and 4
  "item3",
  "item4" 
]
```
3. (this is currently unchanged when rubyfmt'd)
```ruby
# comment relevant to item 1
# comment relevant to item 2
# comment relevant to item 3 and 4
[
  "item1",
  "item2",
  "item3",
  "item4"
]
```

P.s. i discovered this while preparing a PR to rubyfmt (but only the ruby part i don't know rust yet sorry)

**Comment by penelopezone** [comment]
Rubyfmt doesn't currently support end of line comments, so yup this is 100% a valid bug

**Comment by fables-tales** [comment]
this should be fixed now!
