### ISSUE TITLE
Inserts a newline before first comment

### ISSUE THREAD

**Issue by robotdana** [penelopezone/rubyfmt#190]
* Ruby version: 2.7
* Rubyfmt git sha: acade99e80a18b0dcbec1ba908bb37c9301857bb

## Input file

```ruby
#!/usr/bin/env ruby

puts('ok')
```

## Rubyfmt's output

```ruby

#!/usr/bin/env ruby
puts('ok')
```

(that is it starts with an empty line, GitHub UI seems to collapse it.)

## This breaks because

with the initial new line, the shebang is no longer acting as a shebang and the file is executed using `/bin/sh` instead of `/usr/bin/env ruby` which is just syntax errors forever. 

## subsequently rerunning rubyfmt on 

```ruby

#!/usr/bin/env ruby
puts('ok')
```
(that is it starts with an empty line, GitHub UI seems to collapse it.)
gives 
```ruby
#!/usr/bin/env ruby
puts('ok')
```
(no initial empty line.)

which does use the shebang again, which seems like it would be correct, but is kind of still a change in behaviour from the input.

Found while creating #189

**Comment by penelopezone** [comment]
this is a dup of https://github.com/penelopezone/rubyfmt/issues/176
