### ISSUE TITLE
Rubyfmt errors out when method has operator-style name

### ISSUE THREAD

**Issue by HarrisonB** [penelopezone/rubyfmt#194]
* Ruby version: 2.5.8
* Rubyfmt git sha: c7efbb75289cbb48a2910cb0c580686f12eee62a

## Input file

```ruby
foo.[](:whatever)
```

The same error can be reproduced if `[]` is replaced with any of the following:
* `>`
* `<`
* `>=`
* `<=`
* `<=>`
* `-`
* `+`
* `%`
* `*`
* `/`
* `**`
and probably more sets of non-alphabetical symbols.

This same error also occurs without parentheses:
```ruby
foo.[] :whatever
```

## Rubyfmt's output

```
Traceback (most recent call last):
        1: from path/to/rubyfmt/rubyfmt.rb:237:in `<main>'
path/to/rubyfmt/rubyfmt.rb:237:in `format_to_stdout': No variant matched untagged enum Expression. (Error from ripper_deserialize) (RuntimeError)
```

## This breaks because

This is legal Ruby syntax and should not cause an error.

----

Thank you for your work! I'm so excited about this project and really appreciate your generosity to the Ruby community.

**Comment by penelopezone** [comment]
Out of interest, why does your project do this instead of directly `[]` or whatever?

**Comment by HarrisonB** [comment]
This often comes up for my team when using the safe-navigation operator (I removed it here as it didn't affect the actual error):

```ruby
value_that_can_be_nil&.[](0)
```
