### ISSUE TITLE
Breaks on multi-argument setter methods

### ISSUE THREAD

**Issue by mikker** [penelopezone/rubyfmt#196]
* Ruby version: `2.6.6p146`
* Rubyfmt git sha: `c7efbb75289cbb48a2910cb0c580686f12eee62a`

## Input file

```ruby
Capybara.server = :puma, { Silent: true }
```

This is a [multi-argument setter method](https://github.com/teamcapybara/capybara/blob/master/lib/capybara/config.rb#L54-L56). Very weird but apparently allowed.

## Rubyfmt's output

```
Traceback (most recent call last):
        1: from /Users/mikker/dev/rubyfmt/rubyfmt.rb:237:in `<main>'
/Users/mikker/dev/rubyfmt/rubyfmt.rb:237:in `format_to_stdout': No variant matched untagged enum Expression. (Error from ripper_deserialize) (RuntimeError)
```

## This breaks because

I suppose rubyfmt could leave it as is. Alternatively something like `Capybara.server=(:puma, Silent: true)` which would be more descriptive IMO but just as weird if not weirder.

**Comment by mikker** [comment]
Unapologetically fixing with `Capybara.send(:server=, [:puma, {Silent: true}])` for now

**Comment by mcmire** [comment]
Well I learned something new today! I always thought that `Capybara.server = :puma, { Silent: true }` was equivalent to `Capybara.server = [:puma, { Silent: true }]`.

**Comment by mikker** [comment]
Maybe it is and it's doing some sort of pattern matching on the method calling 🤷‍♂️

**Comment by mikker** [comment]
Btw, this was the **\*only\*** thing that broke when I reformatted my whole app's worth of .rb files

```
$ find . -name '*.rb' | xargs wc -l
        …
        14022 total
```

**Comment by penelopezone** [comment]
Confirmed. This minimises to `a = 1, 2`
