### ISSUE TITLE
Removes comments at ends of scopes

### ISSUE THREAD

**Issue by HarrisonB** [penelopezone/rubyfmt#199]
* Ruby version: 2.5.8
* Rubyfmt git sha: dd30aed

**NOTE:** This doesn't technically break behavior as it only removes comments, but I felt prompted to file as #188 remains open. I completely understand if  this is intentional behavior--just wanted to file in case it wasn't!

## Input file

```ruby
# Here is a top-level comment

def foo
  # Here is a comment
  # Another test comment
  puts("here is some code")

  # Here is another comment
  puts("here is some code")

  # Another comment
  
  # Last one
end

# Here is a top-level comment at the end

# Last one for sure
```

## Rubyfmt's output

```
# Here is a top-level comment

def foo
  # Here is a comment
  # Another test comment
  puts("here is some code")

  # Here is another comment
  puts("here is some code")
end
```

## This breaks because

Code generators (e.g. `rails new`) will often include comments as instructions in such positions which are helpful. It also feels very unexpected to have a comment simply removed altogether (though I suppose that is subjective).

**Comment by fables-tales** [comment]
this should be fixed now
