### ISSUE TITLE
RFC: list of methods that shouldn't get parentheses

### ISSUE THREAD

**Issue by penelopezone** [penelopezone/rubyfmt#54]
## Definitely not:

* `require` and `load`
* `to` (as in RSpec)
* anything called at the class level
* `p`
* `puts`, `gets`

## Class methods that get parens

* `define_method` (and family)

Please add suggestions.

**Comment by searls** [comment]
I vote that `puts` and `gets` should go under "definitely not".

**Comment by samandmoore** [comment]
`load` should go up there with `require`

**Comment by samandmoore** [comment]
@samphippen what do you wanna do for rails methods? you already have `to` for RSpec, so i guess this list is meant to be inclusive of non-standard-lib stuff, right?

i think `delegate` wants special treatment, same with `has_one`, `has_many`, `belongs_to`, `validate`, `validates`. i think there's gonna be a lotta rails stuff 😬

**Comment by samphippen** [comment]
updated for comments from @searls and @samandmoore

**Comment by samandmoore** [comment]
@samphippen what about gemspec files? those tend not to use parentheses

here's one pasted example:
```
$:.push File.expand_path("../lib", __FILE__)

require "thing/version"

Gem::Specification.new do |s|
  s.name        = "thing"
  s.version     = Thing::VERSION
  s.authors     = ["...."]
  s.email       = ["..."]
  s.homepage    = "..."
  s.summary     = "..."
  s.description = "..."
  s.license     = "MIT"

  s.files = Dir["{lib}/**/*", "LICENSE", "Rakefile", "README.md", "CHANGELOG.md"]
  s.test_files = Dir["spec/**/*"]

  s.add_dependency 'activesupport', '>= 4.2'
  s.add_dependency 'sinatra', '>= 1.4', '< 3'
  s.add_dependency 'sinatra-contrib', '>= 1.4', '< 3'
  s.add_dependency "webmock", ">= 2.0"

  s.add_development_dependency 'appraisal', '~> 2.2.0'
  s.add_development_dependency "rspec"
  s.add_development_dependency "pry"
  s.add_development_dependency "yard"

  s.required_ruby_version = ">= 2"
end
```

**Comment by samandmoore** [comment]
i guess i'd be fine with those be parenthesized

**Comment by mikker** [comment]
`pp` is also auto-required since 2.5. IMO goes in same category as `puts` and `p`.

**Comment by searls** [comment]
Also an option: not forcing parentheses when invoking methods. 

I worry that a whitelist will never be long enough for everyone and the fact Ruby is used in a DSL-ish way in so many contexts makes a general-purpose tool almost unable to anticipate all such uses

**Comment by mikker** [comment]
@searls is right. Whitelist is going to be either huuuuge or really tiny (and it almost already isn't).

**Comment by aergonaut** [comment]
I would like to suggest `raise` also be added to the "definitely not" list. It looks pretty weird, in my opinion, and I don't think I've ever seen anyone use parentheses with `raise`:

```ruby
raise(ActiveRecord::RecordNotFound.new)

# vs

raise ActiveRecord::RecordNotFound.new
```

**Comment by ianks** [comment]
- the logger family of methods (info, error, etc)
- warn

**Comment by teoljungberg** [comment]
What about the rest of RSpec's DSL methods? `describe`, `context`, `it`, shared-examples and family, etc etc.

**Comment by pjg** [comment]
To add to @searls's suggestion:

> Also an option: not forcing parentheses when invoking methods.

That would be much better than forcing them everywhere apart from a few whitelisted exceptions.

But what would be ideal is this: see if the method call uses brackets in the original code, and use them if it does, but don't force brackets on its own, and also don't remove brackets on its own.

Another solution I can think of is to allow the end-user to configure their own whitelist, but I understand rubyfmt wants to be configuration-less. prettier also has this goal, but allows a couple of most debatable things to be configurable.
